### PR TITLE
Cef74 ( & Python 3.8/3.9 Support)

### PR DESCRIPTION
**Pull request by Berserker66**
Update to CEF 74.1
Also includes https://github.com/cztomczak/cefpython/commit/5848b22c715efac2045bda53960b7a3a2b1d0ae8 and expands it for Python 3.9

Also rips out Python 2.7 in some, not all places. As it officially died on Jan 1st 2020.

Docs aren't updated in many places, only tested on windows x64

### CODE REVIEW

**Comment by cztomczak** [comment]
There are many issues with this PR. Upgrading CEF is complex and I don't accept PRs for major CEF upgrades, because it's hard to get it right.

**Comment by cztomczak** [comment]
There is a related PR for Python 3.8 support: https://github.com/cztomczak/cefpython/pull/594

**Comment by Berserker66** [comment]
Ok, well, if anyone feels adventurous, I put the builds here:
https://github.com/Berserker66/cefpython/releases/tag/Py39

**Comment by 823639792** [comment]
@Berserker66  Ary you try cefpython new version on macos？ How to generate helper file?
My test result is gpu process start failed。
log：
How to generate helper file?
:ERROR:mach_port_rendezvous.cc(311)] bootstrap_look_up .MachPortRendezvousServer.83940: Unknown service name (1102)

**Pull request closed without merging**
