### PR TITLE
Update PyInstaller compatibilty

### PR DESCRIPTION
**Pull request by bwoodsend**
Hello, I'm from PyInstaller.

The 1st commit is just to make your example hook compatible with more recent versions of PyInstaller. 

The second is to have it recognised automatically by PyInstaller - i.e. no need to copy/paste that hook file about.

I haven't tested it yet. We've verified that the hook itself now works but I still need to test the 2nd commit.

### CODE REVIEW

**Comment by cztomczak** [comment]
Is it still compatible with old versions of pyinstaller? Sometimes user want to use an old version due to newer versions of pyinstaller giving more false-positives by Anti-Virus software.

**Comment by bwoodsend** [comment]
Yes it's still compatible with older versions. The `try: except ImportError` takes care of that. The hook won't be collected automatically for PyInstaller 4.0 so that information probably needs to go in the README - that the `hook-cefpython3.py` (which I've moved) still needs to be downloaded and put somewhere findable. Alternatively, we could drop the 2nd commit and instead copy the hook to our [hooks repo](https://github.com/pyinstaller/pyinstaller-hooks-contrib/) where it will also be found by PyInstaller 4.0. This would easier for us to test and would not require users to update `cefpython`.

> newer versions of pyinstaller giving more false-positives by Anti-Virus software

We get loads of reports on this and they're different every time. Sometimes any PyInstaller version is flagged as malware, sometimes none are. [Latest test](https://github.com/pyinstaller/pyinstaller/discussions/5407) says that Python 3.8 is malware but 3.7 is all ok - obviously this is nonsense. I've ran my own tests on it, even as far as to write fake malware to see if it gets detected (it didn't - not once). Certain libraries seems to trigger it but run it again next week then they're all ok again. For obvious reasons, these Anti-Virus softwares don't give any kind of feedback as to what their issues are so we can't know what to change even if we wanted to.

**Comment by cztomczak** [comment]
I don't like the idea of creating a separate package `_cefpython_PyInstaller_hook`. Can't we put the code in our existing `cefpython3` package?

**Comment by cztomczak** [comment]
Compatibility fixed in commit https://github.com/cztomczak/cefpython/commit/686d528b3eebbe5b84a770f5d266aea8dd185721 .

For recognizing pyinstaller automatically please send a separate PR preferably without introducing a new package.

**Pull request closed without merging**
