### PR TITLE
Repairing pywin32 example (#224)

### PR DESCRIPTION
**Pull request by jf-mgd**

### CODE REVIEW

**Comment by cztomczak** [comment]
Thanks for the PR. Code changes are overall good, there are only some minor style issues. I will test it when I switch to Windows machine.

**Comment by jf-mgd** [comment]
> By default there is a random port generated
Yes you can remove this commit, it was for my personals tests, I should not have added that to this branch...

**Comment by cztomczak** [comment]
Related issue: Issue #224 ("Port CEF 1 examples to CEF 3").

**Comment by cztomczak** [comment]
I have tested on Windows 7 with Python 2.7/3.4  and it works fine in default loop mode. However in multi threaded message loop it crashes on exit. Have you noticed this behavior during your testing?

**Comment by jf-mgd** [comment]
Yes, and it was something I wanted to bring to your attention, but I forgot :/
It comes from the fact that there's a call do `CefDoMessageLoopWork` (https://github.com/cztomczak/cefpython/blob/master/src/cefpython.pyx#L965) in `cefpython.Shutdown()`.
Not calling this function when using multithreaded message loop should do the trick, although it's on speculation level as I do not have a Cython compiler to test this hypothesis.

**Comment by cztomczak** [comment]
That makes sense. Created Issue #380 to fix that.

**Comment by cztomczak** [comment]
Thanks. I will make additional changes to the example in a separate commit.

**Comment by cztomczak** [comment]
Additional changes in commit b9875f5cedbadc0c03845798056f6c14cefeaf02.

**Comment by cztomczak** [comment]
@jf-mgd If you would like to add add yourself to the Authors file then please send a separate PR for that. In the authors file you can add and email or a website link next to your name.

**Pull request merged**
