### PR TITLE
Added ARM Support

### PR DESCRIPTION
**Pull request by Hexaflexagon**
Added automate.py --arm-build
Added ARM Lib-Links

libcef.so build tested on Ubuntu 16.04 x86_64
python compile.py tested on Raspbian

### CODE REVIEW

**Comment by cztomczak** [comment]
The active branch is now cefpython56, I see you've closed PR so you probably figured that out too. There are new build tools in the tools/ directory. Scripts in src/linux/ are deprecated. However I haven't yet tested the new tools on Linux, I will do so soon, there might a minor bug or two. New tools were tested so far on Windows and Mac.

OS_POSTFIX2 should be "arm32" and "arm64" I think. Also there must be a corresponding OS_POSTFIX set to "arm" for that platform.

Debian packages are deprecated currently. New build tools support only creating setup installer package and from that package .whl is created which is then uploaded to PyPI.

Is the --arm-build flag required? Isn't that already detected through OS_POSTFIX*? In new build tools there are WINDOWS / LINUX / MAC constants that should be used from now on. We should add ARM constant too.

Just for reference, corresponding issue in the tracker is #267.

**Comment by cztomczak** [comment]
Also docs/Build-instructions.md should be updated. New section should be added with instructions for ARM build. It would also be nice to add some more information.

The --arm-build flag is OK I see now it's for cross-compiling.

**Comment by Hexaflexagon** [comment]
An ARM Linux libcef.so can only be created under Ubuntu x86_64.

I have created a working version, but it did not work again. This is the reason why I closed it.

I will try this with 56 and the new build tools again.

**Comment by cztomczak** [comment]
I suggest you to create a separate branch named "arm-support" in your fork and base that branch on cefpython56 branch. And create Pull Request using that arm-suppot branch. This is the best way to get things done in git, always create a separate branch for your changes.

**Comment by cztomczak** [comment]
Just FYI, the active branch is master from now on. I did many changes to build tools during Mac release.

**Pull request closed without merging**
