### PR TITLE
Fix all DeprecationWarning: invalid escape sequence

### PR DESCRIPTION
**Pull request by BoboTiG**
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>

### CODE REVIEW

**Comment by BoboTiG** [comment]
Out of curiosity, not interested?

**Comment by cztomczak** [comment]
You didn't provide no information, so I'm not sure what is the purpose of this.

**Comment by BoboTiG** [comment]
Oh sorry :)

This fixes `DeprecationWarning: invalid escape sequence`. It is a warning telling us there is something Python cannot understand (when it sees a backslash and try to interpret the following letters, like `\d`, `\xea` ...). Those warnings are now `SyntaxWarning` in Python 3.8 and will become `SyntaxError` in 4.0, so it is a little sanitization patch.

**Comment by cztomczak** [comment]
This forces a module doc comment containing a Windows path to change it to an invalid path. Same for other doc comments in functions, these changes modify commands that become invalid (when copied in editor).

The make-deb.py script is deprecated and shouldn't be modified, as it is not maintainted anymore. 

Changing raw string regular expression requires testing affected code, as it could break things.

I think I will wait for Python 3.8 stable release and fix it when cefpython supports it.

**Pull request closed without merging**
