### PR TITLE
Cefpython57

### PR DESCRIPTION
**Pull request by yattamax**
Hi, this is a my example of how to do a "connection" overriding using an  external library (eg: urllib3) instead of internal netwkork library of chromium

Massimiliano
[ovverride_connection.py.zip](https://github.com/cztomczak/cefpython/files/1503807/ovverride_connection.py.zip)

### CODE REVIEW

**Comment by cztomczak** [comment]
To share your example with others it's best to do it using these steps:
1. Post your example on https://gist.github.com/
2. Create an "override-connection" branch from master in your fork
3. Add a link to your example in examples/README-Examples.md
4. Send pull request

**Comment by yattamax** [comment]
I tried just now.

I don't know if I do the correct steps ... is the first time that I do this pull on github :)

**Comment by cztomczak** [comment]
Example added in commit https://github.com/cztomczak/cefpython/commit/11b444d287804c9a0a56a0cb988938fbea8b9a82 .

**Comment by cztomczak** [comment]
Thanks.

**Pull request closed without merging**
