### PR TITLE
Fix the bug of loading shared libraries.

### PR DESCRIPTION
**Pull request by Xianguang-Zhou**
Purposes:
~~1. Reduce the CPU usage of "qt.py" for Windows.~~
2. Fix the bug of loading shared libraries.

### CODE REVIEW

**Comment by cztomczak** [comment]
How does the "external_message_pump" option exactly affect performance? How did you test it? What versions of qt did you test with? (pyqt4, pyqt5, pyside, pyside2).

What is the bug with loading shared libraries?

**Comment by Xianguang-Zhou** [comment]
On Windows, if the "external_message_pump" option is not true, the CPU usage is about 10%. If the "external_message_pump" option is true, the CPU usage is about 0%.
I tested it with PySide2.

If a process overrides the "LD_LIBRARY_PATH" environment variable, the subprocesses will not be able to find other shared libraries by the original "LD_LIBRARY_PATH" environment variable.

**Comment by cztomczak** [comment]
Please be specific. Tested on what website and what OS? What are you doing in app that it hits 10% CP U?

What other shared libraries CEF Python needs to find in OS through LD_LIBRARY_PATH? Is it your app specific libraries? Provide specific information on your issue.

**Comment by Xianguang-Zhou** [comment]
1. Tested on Windows 10.
I did almost nothing in the application: [qtcef.py](https://github.com/RimoChan/Librian/blob/2b4044e48f13d48ff8fa523f3943e8695061a3d0/Librian_util/qtcef.py)

2. The other shared libraries to find through LD_LIBRARY_PATH are libpython libraries.
For example: libpython3.6m.so.1.0

**Comment by cztomczak** [comment]
The patch is for qt.py example, Does the issue reproduce with the original example on google website?

**Comment by Xianguang-Zhou** [comment]
Sorry, I don't know what the original example on google website you said.

**Comment by cztomczak** [comment]
The one you're sending the PR for.

**Comment by Xianguang-Zhou** [comment]
I'm terribly sorry.
The original "qt.py" has no CPU usage issues on Windows 7.
The cause of the CPU usage issue may be a bug of Windows 10 1809.
So I plan to reset the commit: 5b6aed928cdbba516b6b054023982758dc563161

**Comment by Xianguang-Zhou** [comment]
I have deleted the commit of enabling the "external_message_pump" option.

**Comment by cztomczak** [comment]
I will merge it during next release.

FYI: It might be better to get rid of `LD_LIBRARY_PATH` entirely and link via `rpath/$ORIGIN`.

**Comment by Xianguang-Zhou** [comment]
Thank you very much.

**Pull request merged**
