### PR TITLE
Fix pango library wrong include path (hb.h: No such file or directory)

### PR DESCRIPTION
**Pull request by mcejp**

### CODE REVIEW

**Comment by mcejp** [comment]
By the way, on Fedora there is another problem due to warnings triggered by some GTK headers and `-Werror` being set by tools/build.py, for example:

```
/usr/include/gtk-2.0/gtk/gtktypeutils.h:236:64: error: ‘GTypeDebugFlags’ is deprecated [-Werror=deprecated-declarations]
  236 | void            gtk_type_init   (GTypeDebugFlags    debug_flags);
      |                                                                ^
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from dialog_handler_gtk.h:12,
                 from dialog_handler.h:11,
                 from client_handler.h:14,
                 from client_handler.cpp:9:
```

**Comment by cztomczak** [comment]
Why is harfbuzz required?
So this still doesn't work on Fedora. What version of GTK did you install? Try a newer version.

**Comment by mcejp** [comment]
hb.h is included by some random GTK header. I suppose that if the Makefiles had used `pkg-config` instead of hardcoded paths, this problem would not arise.

My version of `gtk2-devel` is 2.24.32 and `glib2-devel` is 2.64.6.

**Comment by cztomczak** [comment]
This is an issue with Panglo library having wrong include path: https://gitlab.gnome.org/GNOME/pango/-/issues/387
Doesn't look like Fedora specific issue.

**Pull request merged**
